---
- name: Instalação do cowsay
  hosts: host_servers   # Grupo de hosts do inventário
  become: true    # Diz que vai escalonar privilégios. Equivalente ao -b

  tasks:  # Descrição das tarefas que serão executadas

    - name: Instalação do cowsay  # Nome da tarefa
      package:                   # Nome do módulo
        # Argumentos do módulo
        state: present
        name: cowsay
